# Generated by Django 5.1.4 on 2025-01-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='horario',
            new_name='hora',
        ),
    ]
