# Generated by Django 5.1.4 on 2025-01-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0002_reservar_rename_horario_reserva_hora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.RenameField(
            model_name='reservar',
            old_name='horario',
            new_name='hora',
        ),
    ]
