# Generated by Django 5.1.4 on 2025-01-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRestaurante', '0003_delete_reserva_rename_horario_reservar_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario_acerca_restaurante',
            name='valoracion',
        ),
    ]
